project_id = "hrtyncnxnbdteccigzav"

[functions.guesty-listings]
verify_jwt = false

[functions.guesty-inquiry]
verify_jwt = false

[functions.guesty-availability]
verify_jwt = false

[functions.import-drive-assets]
verify_jwt = false
