
CREATE TABLE public.services (
  id SERIAL PRIMARY KEY,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL DEFAULT 0,
  type TEXT NOT NULL,
  unit_cost NUMERIC,
  sub_text TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.bookings (
  id BIGSERIAL PRIMARY KEY,
  guest TEXT NOT NULL,
  checkin DATE NOT NULL,
  checkout DATE,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  cc_fee_on BOOLEAN NOT NULL DEFAULT false,
  tip_mode TEXT NOT NULL DEFAULT 'amount',
  tip_value NUMERIC NOT NULL DEFAULT 0,
  tip NUMERIC NOT NULL DEFAULT 0,
  cc_fee NUMERIC NOT NULL DEFAULT 0,
  total_guest NUMERIC NOT NULL DEFAULT 0,
  total_profit NUMERIC NOT NULL DEFAULT 0,
  saved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all on services" ON public.services FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on bookings" ON public.bookings FOR ALL USING (true) WITH CHECK (true);

INSERT INTO public.services (category, name, price, type, unit_cost, sub_text, sort_order) VALUES
('Sailing & Boats','Ally Cat — 3h',20000,'mgmt',NULL,'Up to 10 guests',1),
('Sailing & Boats','Ally Cat — 4h',24000,'mgmt',NULL,'Up to 10 guests',2),
('Sailing & Boats','Ally Cat — 6h',36000,'mgmt',NULL,'Up to 10 guests',3),
('Sailing & Boats','Fat Cat — 3h',32500,'tour',NULL,'Up to 20 guests',4),
('Sailing & Boats','Fat Cat — 4h',42000,'tour',NULL,'Up to 20 guests',5),
('Sailing & Boats','Fat Cat — 6h',52500,'tour',NULL,'Up to 20 guests',6),
('Sailing & Boats','Fat Cat Whale Watching (adult)',1600,'tour',NULL,NULL,7),
('Sailing & Boats','Fat Cat Whale Watching (child)',1200,'tour',NULL,NULL,8),
('Sailing & Boats','Private Boat Tour — 3h',9500,'tour',NULL,NULL,9),
('Sailing & Boats','Private Boat Tour — 4h',11500,'tour',NULL,NULL,10),
('Sailing & Boats','Fishing Charter — 4h',10000,'tour',NULL,NULL,11),
('Sailing & Boats','Spearfishing — Inshore',12000,'tour',NULL,NULL,12),
('Sailing & Boats','Spearfishing — Deep Water',21000,'tour',NULL,NULL,13),
('Surf — Victor','Beginner Lesson — Sayulita',1200,'tour',NULL,'Per person',1),
('Surf — Victor','Punta de Mita Session (La Lancha)',2000,'tour',NULL,'Per person',2),
('Surf — Victor','Surf Guiding — Intermediate',2500,'tour',NULL,'Per person',3),
('Surf — Victor','Advanced Coaching & Guiding',3500,'tour',NULL,'Per person',4),
('Surf — Victor','Boat Trip Surf Safari',15000,'tour',NULL,NULL,5),
('MiChula Tours','Whale Watching',10100,'tour',NULL,NULL,1),
('MiChula Tours','Canopy Zipline',2000,'tour',NULL,NULL,2),
('MiChula Tours','ATV Single',2500,'tour',NULL,NULL,3),
('MiChula Tours','ATV Double',3300,'tour',NULL,NULL,4),
('MiChula Tours','RZR (up to 4 pax)',7600,'tour',NULL,NULL,5),
('MiChula Tours','Horseback Riding',1400,'tour',NULL,'Per person',6),
('MiChula Tours','Monkey Mountain (1–3 pax)',1700,'tour',NULL,NULL,7),
('MiChula Tours','Monkey Mountain (4+ pax)',1300,'tour',NULL,'Per person',8),
('UTV Rentals','Can-Am Maverick 4-seater',2500,'mgmt',NULL,'Per day · 2-day min',1),
('UTV Rentals','Polaris Ranger 6-seater',2200,'mgmt',NULL,'Per day · 2-day min',2),
('UTV Rentals','UTV Gas',1500,'mgmt',NULL,'Flat charge per fill',3),
('Wellness','Yoga / Movement',2500,'margin',1500,NULL,1),
('Wellness','Breathwork',2500,'margin',1500,NULL,2),
('Wellness','Sound Bath & Healing',3000,'margin',2000,NULL,3),
('Massages','Relaxation Massage',1500,'fixedprofit',500,NULL,1),
('Massages','Therapeutic Massage',1500,'fixedprofit',500,NULL,2),
('Massages','Deep Tissue Massage',1500,'fixedprofit',500,NULL,3),
('Massages','4-Hands Massage',2500,'fixedprofit',500,NULL,4),
('Massages','Prenatal Massage',1700,'fixedprofit',500,NULL,5),
('Massages','Lymphatic Drainage',1700,'fixedprofit',500,NULL,6),
('Massages','Hot Stone Massage',1800,'fixedprofit',500,NULL,7),
('Massages','Cupping Therapy',1800,'fixedprofit',500,NULL,8),
('Massages','Reflexology with Salts',1100,'fixedprofit',500,NULL,9),
('Spa Treatments','Manicure',1200,'margin',700,NULL,1),
('Spa Treatments','Pedicure',1200,'margin',700,NULL,2),
('Spa Treatments','Body Scrub & Wrap',2800,'margin',2300,'90 min',3),
('Spa Treatments','Facial Cleansing',1800,'margin',1300,NULL,4),
('Food & Culinary','Cachasol Distillery Tour',1500,'tour',NULL,'Per person',1),
('Food & Culinary','Private Cooking Class',1200,'tour',NULL,'Per person',2),
('Food & Culinary','Sayulita Taco Tour',1200,'tour',NULL,'Per person · min 4',3),
('Groceries & Drinks','Groceries & Shopping',0,'grocery',NULL,'Enter cost paid — 35% markup auto-applied',1),
('Groceries & Drinks','Beer — 6-pack',0,'beer',NULL,'Enter wholesale cost · guest charged $480/pack',2),
('Villa Services','Fully Stocked Pool Mini Bar',0,'grocery',NULL,'Enter cost of stock — 35% markup auto-applied',1),
('Villa Services','Sunset Private Bartender — 3h',2800,'villa',NULL,'Min 4 guests flat rate',2),
('Villa Services','Bartender — Extra Person',900,'villa',NULL,NULL,3),
('Villa Services','Margarita Pitcher Add-on',1000,'villa',NULL,NULL,4),
('Villa Services','After-Hours Dinner (service fee)',500,'villa',NULL,NULL,5),
('Villa Services','Beach Fire Preparation',1000,'villa',NULL,NULL,6),
('Transportation','Airport Transfer (round-trip)',5000,'flat',4000,NULL,1);
